const appData = {
  collectors: {
    "MA": "Ahriani, S.Si",
    "MTs": "Putrini Idamanti, S.Pd",
    "SMP": "Nurul Faudziah, S.Pd"
  },
  students: {
    "MA": {
      "10": ["AIDIL FITRAH RAMADHAN", "A. ZAKY ATTAMAM IHSAN", "AYLA RAFILAH", "HALIL GIBRAN", "SYAHRUL RAMADHAN", "FAIZ AL FAQIH", "NUR FAJRIN", "AISYAH AFIQAH SUARDI", "ZUL FADLI", "A. ZIDAN FAQIH MAULANA. N", "NUR ASIFAH", "AHMAD SOFYAN", "AHMAD ZAKY MAFTUH SYAM", "A. MUKHLISA NAYLATUL HIDAYAH", "MUH. IMTIYAZ MUYASSAR PARELA", "LUTFIA NADIFA", "WIFAQ AZIZAH", "A.ALZENA AZALIA", "WAHYUDI", "IKRIMA NURUL INAYAH", "DIRGAM IBADURRAHMAN", "DHEA PUTRI", "IKHSAN FIRDAUS", "NAURAH PURNAMA", "NURUL AZIZAH RAMADHANI", "A. UMMU FAKHIRA M", "AMIRATUL MUKTAZZAH", "KHANABELA NAYARA HADIANSAH", "NURUL BIL HIKMAH R", "FATHIMATURRODIYAH", "MUH RAFI AL-KHALIS", "IBNU DZAKY", "HAFIDZATUL AQILAH", "SYIFA LATHIFA", "NAYLA YASMIN", "ANDI NURGANDINI", "M. DHAFA ATHILLAH", "NUR ALIF", "ASQA AQILLA", "MUH AKRAM KADIR", "MUHAMMAD FIQRI", "M. AIDIL MAULANA SAPUTRA", "RADIANA GAFUR", "WAHYUNI NURANNISA", "ALYA KHUMAIRAH", "FAHD ARYA AIDAL", "JUSRAN", "MUH FAIZ AIMAN", "NAUFAL RUSYAIDI ASMAN", "RESTU GIBRAN AL-FARISA", "ASRAH AFIFAH", "AZIFA MUFIDAH", "DHIA NOOR KHALISAH IHSAN", "NAJWA NUR FASIHA", "NUR AFNI PRATIWI", "PITASARI", "RABIATUL ADAWIYAH", "RIFQAH ULVIYATUL ASRAH", "SYAKINA", "WAWAH AULIYAH PUTRI"],
      "11": ["AFDAL", "KAIZAR ARTA PUTRA", "AHMAD MUZACKY", "ANDI SOFYAN NUR", "ICHSAN SAPUTRA", "MUH. DAFFAH AWRI", "MUHAMMAD ZULKIFLI LUKMAN", "MUH. ADILAH RASYA PUTRA", "MAULANA MALIK IBRAHIM", "MUH. ALTHAF SAMSUL", "NURYASIN", "ZHAKY SYAFRAN NUR", "ALAMSYAH", "MUL KHARIFAL GAZALI", "AWAL MAULANA", "AIDAN ARUNK TANRIBALI", "AHMAD SYADDAD MUARIF", "MUHAMMAD FAIZ", "GIGA TERA HALIL", "AIMY RAMADHANI.N", "ALIYAH APRILIA", "ANDI IIN FEBRIANA", "HILYA", "MAGFIRAH NURUL FADHILA", "NUR AFIKA RAUF", "MUALIFA IHSANI", "AQILAH MUSYARRAFAH", "A.ALYA AL-FADHILAH SUKRI", "MAWAR", "KAILA ALIFIYAH", "NABILA ALAMANDA", "NURAZIZA SALSABILAH", "QURRATA A'YUNIN", "NUR AFIKAH", "KASYIFA SYAKAYA AS", "NURUL DZAFIKA", "NURILMI", "NUR HALISA", "NURUL FAJRIA", "WAHYUNI", "ZAKIYAH AZZAHRAH PUTRI", "ALIFIAH QURROTA AYUNI", "AFIFAH", "AULIA PRATIWI", "FATIMA", "HASRI AYNUN AZ ZAHRA", "NURZAKIAH", "ALVINA AZ-ZAHRAH", "UMMUL KHAIRAH ROSYIDAH", "MUTMAINA", "ASYILA AZZAHRA", "ANDINI REZKI DAMAYANTI", "NAYLA AFIQAH FAKHIRAH", "WANITA RAMADINA", "WIDYA FANI ASRIANI", "LUTFIAH AL-FALISA", "NURUL AFRILIA PUTRI", "NURUL MUTHMAINNAH", "WADDATZ MAWADDAH", "KHAERUNNISA AZZAFA", "YUMNA FAKHIRA", "KIFKA IHSANI RAMLI", "NAJWA NURUL BARQAH", "A. NUR ASIZAH", "ZASKIA QALBI", "AULIA ZHAFIRHA", "ZASKIYAH LUTFIYAH"],
      "12": ["NUR RAHMAT QADRI S", "M. DAFFA ALMER JAMAIL FADLI", "AHMAD ZAKY FAIRUZZABADI", "ANDI BAITUL AQSHA", "REZKY IRADAT", "A.MUH.IRHAM", "MIFTAAHUL ARSAAQ", "MUJAHIDIN NUR", "MUH.WILDAN", "A. FIQRUL MASYURI", "RIYAZUL ISLAM", "ANDI ISDAR NUR", "M ALIL KADRI", "MUH ASYRAFUN NAS", "MUH. DIRGA", "FADHEL IKHSAN", "MUH. MUJTAHIDURRIDHO", "KAIZAR YUSRIL", "IBNU AWAL RAMADHAN", "NUZUL HARDIANSYAH", "SAHRUL", "ALIF YUDHA SATRIANSYAH R", "AHMAD ADRIAN", "ALDI ALAMSYAH", "RAHMAT FAUZI", "MUH. AYYAS AL-FAID", "AFDAL RIFAID", "ABD. HAFIZH HARIS", "ABIZAR ALGIFARI", "AHMAD AFIF FAYYADH", "FADHIL JAILANI JAPAR", "MUH.DZAHWAN ALJAZIR", "HAIKAL AKBAR", "ABYAN RAIHAN", "FARID INDRA", "MUHAMMAD LUTHFI", "MUHAMMAD SYAHRUL RAMADHAN", "MUHAMMAD SYAHRIL RAMADHAN", "THALITA MUTI'AH", "IZMUL AZZHAM", "ANDI ARIFA MULYANI NUR", "RAHMA INAYAH", "MAGFIRAHTUL JANNAH", "SASKIA", "INDRI PUTRI MAULIDIA", "LESTI ENDRIANI", "ANDI SITI HUMAIRAH", "NURFADILA", "FATHIYATUL AISYA", "SUHAIMATUL KHAERA", "TINA AMELIA", "RESKI AULIA PUTRI", "TIYARA", "NANDA MAHELLHESYA", "QURRATUL AIN", "NAFISA KHOIRUN NISA", "A. KARMILA", "AMELIA PUTRI ALTHEA", "NUR AZIZA MAHARANI", "NUR RAHMA MAWAR", "RESKI AWALIA MARSYA", "IZZATUN NISA", "NURUL NABILA AMATULLAH RESTI", "A. ANNA ALTAFUN NISA", "ALYA THALITA AZILAH", "ADIRA VEGA YULIANTI", "MUWAFIQ AZIZAH", "NABILA WAHYU", "NURFADILLAH", "PUTRI ZAHIRAH AMIR", "NORINE SULAIMAN", "NURSALINA PUTRI DARTI"]
    },
    "MTs": {
      "VII A": ["A. NUR ATHIFAH", "ADELIA PUTRI", "ANDI ATHALIA MAHARANI", "ANNISA TSARIYYAH SAFIYYA", "DIVA AINUL HAYAT", "FITRI MUBARAK", "HILYAH FIKRIYAH HASAN", "INAYA AZMI ATHIFA", "MAWADDAH NUR AFIFAH", "NADRATUL AYYUN", "NHINDIA AWALIA ANSAR", "NUR ANNISA ANGGRAENI", "NURSYA", "PUTRI KHUMAIRAH", "UFAIRA NURALIFA"],
      "VII B": ["ALIYAH MUSTIKA ALAM", "ASILAH INAYAH DARMAN", "ASYIFA SYARIF", "AULIA RAMADHANI HERLIN", "DZAKIRA TALITA ZAHRA", "KAILA NURKHAFIFAH. HR", "LATIFAH NUR ADIBAH", "NUR AINUN AZZAHRA", "NUR ASIFA SHARAH", "NUR FADILAH", "PASTABIQUL KHAERAT", "SALSABILA NUR ADHA", "UFAIRAH NUR AFIFAH", "YAUMUL ISHAQIAH SYAHRAYA"],
      "VII C": ["A. RAHMAT TANGKE ALINGE", "A. RAYZHA FABIAN IKHSAN", "ABIT PRATAMA", "ABYAN NAKHLA RAFIE", "ACHMAD GIBRAN", "AGHA ABDILAH ATHAYA", "AHMAD FATAHILLAH GAFUR", "AKHNAF ASYRAF ASYHARI", "ARIQ RIFID ALFATIH", "AWWAB AR RAABIH", "AZKA KHAIRUL", "BILAL IMAN", "DWIKY RAHMAT AL HAFIZ", "FAKHRI YASSARR", "KHAIRUL DARRY ABIYYU", "M.RIFQIE NADIM UKAIL", "MUH IMAM AL FARABI IBNU ILYAS", "MUH. ASRAR ABU KHAER", "MUH. SYAHRULLAH", "MUHAMMAD ABDILLAH FITRA", "MUHAMMAD AIDAN SYAHM", "MUHAMMAD ALIF SAPUTRA", "MUHAMMAD DZAKWAN FAUZI MATTALINRI", "MUHAMMAD FARID ATALLAH JUFRI", "NADHIL ZAIDAN", "NURDIN", "RIFQI MUKHTARULLAH", "SAYYID RAMADHANY SYAM"],
      "VIII A": ["Afra Adhwa Mumtazah", "Akifah Nayla Jamal", "Alisyah Inayah", "Anindi Zahra Fadila", "Aqila Al-Khawarizmi", "Ayatul Husna", "Dzakirah Khansa Ramadhani Asbar", "Fauziah Ulfa", "Hipnati Zalsabila", "Inayatul Azmi Atifah", "Khaira Nadifa Apriliya", "Nabila", "Nur Abidah", "Nurazalia Fahira", "Nurul Arifah", "Qanita Maryam Jameela", "Raehana Magfirah", "Rizqy Atiqa Raihanah", "Zuhrah Nindia Alfy"],
      "VIII B": ["Aila Khanza Azahrah", "Aliya Nur Fitri", "Andi Naura Fatimah Ali", "Anisa Mufidah", "Aqila Mughny Shaliha", "Asmaul Husna", "Asnah", "Ayla Azzahra", "Azzahra Syaila Raudyna", "Dewi Anggraeni", "Nasywa Mutiara Aulia", "Nur Indah", "Qurratu Aini", "Raisa Humairah", "Rezki Alfia Febriana", "Rosnia", "Salwa Khumairah", "Zafira Nur Ramadhani"],
      "VIII C": ["Abdul Basith Abnah", "Abil Arqam", "Ahmad Fahreza. S", "Aliful Islami", "Ameer Zacky Syam", "Hasan Basri", "Ilal Alyahya Abbas", "Indar Hidayat", "M. Hilmi Asy'ari", "Muh Agung Ayatullah", "Muh. Alif Al Gifari", "Muh. Yusran", "Muh. Zaidan Riziq Khatam", "Muhammad Abidzar Al Ghifari", "Naufal Muflih Muwaffaq", "Taufiq Rahman. A"],
      "VIII D": ["Abu Yazid", "Ahmad Muarif", "Akhmad Farhan", "Annur Sakti Yusuf", "Athar Reski Yudistira", "Istiqlal Triansyah", "M. Ilham R", "Muh. Irfandi", "Muhammad Restu", "Muhammad Yusran Arafah", "Naufal Pradipta Pratama", "Raehan Syaputra", "Rahmatul Adhar", "Resky Aditia", "Zaim Afiq Rifai", "Muhammad Abidzar Al-Imran"],
      "IX A": ["Akratul Faiza", "Alicia Azalea Queenza", "Arezky Ananda", "Atilah Ainul Hayat S.", "Azkiyah Al Walidah Jamal", "Fhatimah Nailatul Izzah", "Ima Haura Zulfa", "Jihan Alifatuzzahira", "Khulwana", "Melati", "Naysila Az Zahra", "Putri Salsa Nabila", "Salwatul Kamariah", "Suci Ramadhani", "Triana Tasmirah Taufik"],
      "IX B": ["Adelia Azzura Asril", "Ajeng Maharani", "Asmaul Husna", "Dafia Nazwa Azura", "Helga Raissa Febriana", "Inayah Fadilah", "Kasmira", "Myiezha Putri Asrul", "Nur Atihfa Auliah", "Putri Suci NurBarokah", "Razqiyah Mutiara", "Shofiyah Ashila", "Silfatul Zahra", "Tri Syahrini Julia", "Uqailah Sarah Saud", "Wahdaniyah"],
      "IX C": ["Aidh Al Abqary", "Ahmad Ghifari Embas", "Alfian", "Alfino", "Faiz Adman Suhardi", "Fajrin", "Iswandi", "M. Wahyu Walfarih", "Mirza Dhiyaulhaq", "Muhammad Misyal", "Muhammad Qhabil Al Fitrah", "Nawal Alif", "Raja Syafiq", "Triadi Eka Putra", "A. Rifky Mutawaly", "Alfareza Ahza Pratama", "Alif Alfaz Qurana", "Alif Mubarak Ramadhan", "Andi Muh Afkar Idrus", "Andi Muhammad Fadhil Ghazali", "Irzyam Muh Chairil", "M. Sukri", "Muh Ziyahuda Alfaizi", "Muh. Abyang", "Muh. Sayyid Mubaraq", "Muhammad Asyraf", "Nuralamsyah Putra", "Syauqi Fadhlu Rachman Hamka"],
      "IX D": ["Aidil Nur", "Andi Muh Rifqi", "Asqa Aqilla", "Paril", "Hisbullah", "Ikhsan Firdaus", "M. Aidil Maulana Saputra", "Muh Akram Kadir", "Muh Rafi Alkhalis", "Muh. Al Qadri Pratama", "Muh. Habibur rahman", "Muh. Khafiz", "Muhammad Fiqri", "Muhammad Ridwan", "Wildhan Ramdhani"]
    },
    "SMP": {
      "VII A": ["A. ABDUL RAHMAT", "A. MUH. IRGY ALFAHRURAZY, MS", "ABD. JAZIL", "ACHMAD KHALIL", "AFDHAL AL MAHIR", "AHMAD HAIKAL", "AHMAD NAUFAL ELFATIH", "AHMAD PAREL", "AHMAD RAMDHANI", "DZAKWAN DANI RAMADHAN", "DZAKY AHMAD RUSTAM", "FAHRI ZAFRAN KHAIRY", "FATIH AIMAN ATHMAR", "MUSTAJAB AL MUKKARAMAH", "NURMAULANA"],
      "VII B": ["ABRAHAM SYALI SYRACH", "AHMAD FATIR", "DIYAUL HAFIQS", "FAKHRI ZAFRAN KHAIRY HARDIL", "FATHAN ABYU SYAM", "GENTZA AL KHALIFI", "HAIRUL AKBAR HABIBI", "HASBY AL AYUBI", "IDRIS MARHAN", "MUH FARID AL FAJRI", "MUH NAUFAL AFKAR", "MUH SABRI", "MUH. UKASYAH AL MUHSYAM", "MUHAMMAD ABRAR PRANAJA", "MUHAMMAD ASLAM KHIRUL ANAM", "MUHAMMAD NUR IKHSAN", "MUHAMMAD SAENAL"],
      "VII C": ["A QANITAH DZAKIRAH JAIS", "A. QISYA ATTAMAM IHSAN", "ADEEVA BALQIS QOTRUNANDA", "ADILAH LUTFIANI", "ADZKIA MUFIDAH", "AFIQA NURUL MAULIDA", "AGUS RIYANTI", "AISA NURIL IZZAH", "AISYA AZKIYA", "AISYA NUR IZZAH.H", "ALIYAH SYAKIRAH AWAL", "ANINDITA KEISHA AZZAHRAH", "AQILA KHAIRNNISWA", "ASMAUL HUSNA", "FATINA AYLA QOTRUNNADA", "NURINA AWALIA HIDAYAT", "UFAIRA NUR AFIFA"],
      "VII D": ["ADELIA", "ASMAUL HUSNA R", "AULIA RAMADHANI HERLIN", "AZZAHRA ASYILA", "AZZAHRA RAMADANI", "DZAKIRAH PUTRI YUKIN", "HANI KHALILAH SHABIHAH", "ISLAMITA SUCI RAMADHAN", "NAURA ALIFIYAH JAFAR", "NUR AFIFAH FIRANI", "NUR INAYAH ZAIR", "NURUL FAIQAH AMIRAH", "SULHA ATH-TAHIRAH", "SYIFA AULIA PUTRI", "UMRAHATUL MUBARAK BAHTIAR", "ZALFA ALMAIRAH"],
      "VIII A": ["AHMAD KHAERUL", "ANDI FAWWAZ IFTIKHAR UMAR", "ARKAN ARSALAN MARKO", "DALFIAN HAIKAL AL KHALISA", "FAUZAN SAPUTRA", "FURQAN AL FIQRI", "MUH AKIL", "MUH FAHRIAN RAMLI", "MUH IKRAR ANUGRAH", "MUH ILHAM", "MUH SYAHRIR", "MUH. DHAINUL HAQ", "NAUFAL AFIF", "RAHMAT HIDAYAT", "RIFQI PRATAMA IRAWAN", "SAHRUL RAMADAN", "SYAHRUL YASIN SHALEH", "WAFIQ YULLAH", "MUHAMMAD ARKAN AL QIFARI"],
      "VIII B": ["A. ZAHWA AZZAHRA", "ADELIA SYAPUTRI USMAN", "AQILAH KHUMAIRA", "ASSYIIFA BRILLIANA ARIF", "AYATUL HUSNA", "DAIMAH AMRI", "FAEEZA ARYA LATIEF", "FIKRIATUL UMMAH", "INAYA AZMI ATHYFA", "IZZAH INSYIRAH RAMADHANI", "NUR AINUN ASFIAH", "NUR SYAQILAH", "NURUL FITRIA", "RASHIFAH RAMADHANI", "RISQHI FATIMAH AMALIYAH", "SAFIRATUL MAHROSHA", "SALSABILA", "SITTI HUMAIRAH", "SYAKIRAH AGNIA", "SYAKIRAH IZZATUNNISA", "YUMNA AMIRA SYAM", "AQILA DEWI KHUMAIRA"],
      "VIII C": ["A. AMATUL FIRDAUZY", "A. RESKY RAMADHANI", "ALIYAH JAZIAH ASRI", "ALYA HAQQ", "ANDI WADIAH NURUL ASHILAH", "ANNISA AULIAH AZZAHRA", "AQIFA NAILA", "FATIN ZAHIRA AZZAHRA", "HAYATUL ILMI", "KIANDRA AQILA KAMIL", "NAIRA RAIHANA", "NAURATUL MATMUNA", "NAYYA MOULI DIFANI AZZAHRA", "NUR AFIFAH", "NUR AMELIA REZKY", "NUR AZIZAH FIRANI", "NURAFIFA AZZAHRA", "NURUL ASYFA AKSAN", "ST AISYAH RAMADHANI", "UFAIRA NUR AFIFA H", "ZAHRATUL AWALIA", "INAYAH AZMI ATHIFA"],
      "IX A": ["Abid Fadhil Abyan", "Ahmad Al farabi", "Ahmad Fatir Muriadi", "Andi Farhat Mustahrim", "Andi Ibtitan Khaerilirrahman", "Andi Muh. Farid Azhar", "Andi Muhammad Syahban Khaerani", "Andi Wali Nur", "Arib Khoirullah", "Aril", "Arpan", "Azka Faeza Ramadhan", "Bintang Ashabul Kahfi", "Fauzan", "Firdaus Ridwan", "M. Bumi Arafah", "Moh. Al Yasir Arafah", "Muh Hudzaifah", "Muh. Adil Al Fatih", "Muh. Ahyar Adiaksa Achmad", "Muh. Alwan Nur", "Muh. Fathul Ahsan", "Muh. Khairil Hidayat", "Muh. Nurzul Wal Ikram Jafar", "Muhammad Abdi", "Nur Fajri", "Hasrat Nadher Hamzah", "Rehan", "Satria Muhammad Ishaq", "Wahyudi Wahid", "Wildan Resky Mubarrok", "Andi Ahmad Kaysan Qudaratullah"],
      "IX B": ["Adzkia Alya AlMayrah", "Ailsa Alfiyyah Ufairah", "Andi Fatimah Azzahra", "Atsila Maharani Asra", "Faisah Salsabilah", "Farsyah Salsabila", "Faza Aufanida Pangara", "Luthfiyah Septiara", "Miftahul Ainun Rezky", "Natasya Nurfaiza Muadzatun", "Nikmatuzzahra Amin", "Nur Aqilah Maulidya", "Nur Zalzabila", "Nuraliyah Khairunnisa", "Nurfaidah. JM", "St Nur Haura Inas", "Syafika Sebriani Waworuntu", "Yumna Nur Fadila", "Zalzabila Atika"],
      "IX C": ["Adea Mulia Thahir", "Afifatul Mukarramah", "Aisyah Luthfiah Alsyah", "Ajwa Nuriel Azizi", "Andi Fathia Salsabila", "Athifa Elisya", "Fahriani Farah Adiba", "Azizah Nurfajriani", "Hasmiranda", "Ikhfa Nur Andini", "Mahdiyah Zakiyah", "Nisrina Dwi Atifa", "Nur Afia Zahra", "Nur Ihwana", "Nur Maulidya", "Nurkainnah Mustafani", "Rezkiya Rana Ramadhani", "St. Fahma Farzana Azzahrah Idris", "Zalzhabila Putri Kusuma", "Andi Fahira Azzahra Nur", "Revi Anastasya"]
    }
  }
};
